- name: Installing docker python bindings
  become: true
  pip:
    state: present
    name:
      - docker
      - pyyaml>=3.11
      - docker-compose>=1.7.0

- name: "Downloading Harbor {{ harbor_version }} (offline installer)"
  get_url: url={{ harbor_url }} dest=/tmp/harbor.tgz validate_certs=no

- name: "Creating Harbor directory... ({{ harbor_install_dir }}/harbor)"
  file:
    path: "{{ harbor_install_dir }}"
    state: directory
    mode: o+r

- name: "Uncompressing Harbor installer..."
  unarchive:
    remote_src: True
    src: /tmp/harbor.tgz
    dest: "{{ harbor_install_dir }}"
    creates: "{{ harbor_install_dir }}/harbor"

- name: Read template file
  slurp:
    src: "{{ harbor_install_dir }}/harbor/harbor.yml.tmpl"
  register: harbor_yml_tmpl

- name: "Combine harbor config with template"
  set_fact:
    harbor_yml: "{{ harbor_yml_tmpl.content | b64decode | from_yaml | combine(harbor_config, recursive=True) |  combine(harbor_extra_config, recursive=True) }}"

- name: "Write combined config to harbor.yml"
  blockinfile:
    create: yes
    block: "{{ harbor_yml | to_nice_yaml }}"
    path: "{{ harbor_install_dir }}/harbor/harbor.yml"

- name: Running Harbor installer...
  become: yes
  command: "./install.sh {{ harbor_installer_with }} {{ harbor_installer_extra_args }}"
  args:
    chdir: "{{ harbor_install_dir }}/harbor"
    creates: '{{ harbor_install_dir }}/harbor/harbor_install_log.txt'

- name: "creating projects..."
  uri:
    url: "{{ harbor_api_url }}/projects"
    method: post
    user: "admin"
    password: "{{ harbor_admin_password }}"
    status_code:
      - 201
      - 409 # already created
    body_format: json
    force_basic_auth: yes
    return_content: yes
    body: "{{ lookup('template', 'templates/create_project.j2') }}"
  with_items: "{{ harbor_projects }}"
  register: response
  changed_when: response.status == 201

- name: "Creating users..."
  uri:
    url: "{{ harbor_api_url }}/users"
    method: POST
    user: "admin"
    password: "{{ harbor_admin_password }}"
    status_code:
      - 201
      - 409 # already created
    body_format: json
    force_basic_auth: yes
    return_content: yes
    body: "{{ lookup('template', 'templates/create_user.j2') }}"
  with_items: "{{ harbor_users }}"
  register: response
  changed_when: response.status == 201
